### ISSUE TITLE
Issue: Most recent Beta release not working correctly. 

### ISSUE THREAD

**Issue by mattssn11** [SpaceK33z/web-to-plex#101]
**Describe the bug**
So I was working with @Ephellon to try to get the most recent beta release working with plex web app support, he was able to fix it so my settings saved correctly, I reinstalled the application and reconfigured from scratch, my settings will now save and I have made sure to fill out all the required options, but now when I enable Plex or Trakt I get the menu on those pages but the indicator color is grayed out and I have no option to watch or add to radarr/sonarr

**To Reproduce**
I just reinstalled latest commit and set up options, chose the Plex site and the Trakt site and navigated to a specific movie on both and lack the options in the menu. 

**Expected behavior**
to have the options to watch or add to Sonarr / Radarr

**Screenshots**
Plex showing correct server selected: 
![image](https://user-images.githubusercontent.com/54347017/65824574-42428f80-e220-11e9-840b-5b09791f774b.png)

Radarr showing it is configured and has correct information for my instance:
![image](https://user-images.githubusercontent.com/54347017/65824579-59817d00-e220-11e9-82ef-0851894e798b.png)

Sonar showing it is configured and has correct information for my instance: 
![image](https://user-images.githubusercontent.com/54347017/65824583-6e5e1080-e220-11e9-8c50-3c957bbf9203.png)

Settings showing that I have selected both Trakt and Plex to be enabled:
![image](https://user-images.githubusercontent.com/54347017/65824623-ecbab280-e220-11e9-92bb-f2ea65344254.png)

Trakt Showing the Web to Plex menu but no option to watch or add to Sonarr / Radarr:
![image](https://user-images.githubusercontent.com/54347017/65824590-977ea100-e220-11e9-92d0-477c84e80297.png)

Plex Showing the Web to Plex menu but no option to watch or add to Sonarr / Radarr:
![image](https://user-images.githubusercontent.com/54347017/65824600-bf6e0480-e220-11e9-8ace-9f1a7eef7e89.png)

**Extension Information**
 - Version: [e.g. 4.1 Beta]
 - Source: [Github SRC]
 - Browser: [Brave]

**Additional comments**
Add any other comments about the problem here, such as how often the issue occurs, any new changes, etc.

**Comment by Ephellon** [comment]
Found the problem, was in `plugn.js`, the variables weren't initialized correctly. Will link a quick-fix to try here.

**Comment by Ephellon** [comment]
See [beta-branch](/SpaceK33z/web-to-plex/tree/beta-branch) for the fix

**Comment by Ephellon** [comment]
Found a minor saving error on the options page, investigating...

**Comment by Ephellon** [comment]
Back from med-leave, still investigating options page

**Comment by Ephellon** [comment]
Moving "options page" to new bug...
