### ISSUE TITLE
Think about renaming

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/web-to-plex#12]
The name "Movieo to Plex" is not correct anymore since it can also add a button on IMDb.

Name ideas:

- Plexify
- Movie to Plex
- Web to Plex
- Add to Plex

**Comment by NHDriver4** [comment]
I like Web to Plex! Or Web2Plex for short?

**Comment by SpaceK33z** [comment]
Cool, Web to Plex it is! I also like it more, "Add to Plex" can be confused with Plex' chrome extension "Plex it!" (and they may not be happy about that), and "Plexify" is wordplay on Plex, which companies often don't like.
