### ISSUE TITLE
Issue: Foreign Titles

### ISSUE THREAD

**Issue by Ephellon** [SpaceK33z/web-to-plex#121]
> ...[There are 2 issues I still have]: the extension gets deleted every single time Firefox restarts; that might be due to the way developer settings are designed (but settings remain). [F]oreign titles struggle to get a match in the extension even if they exist in Radarr.

_Originally posted by @NicoLeOca in [#104.546454106](https://github.com/SpaceK33z/web-to-plex/issues/104#issuecomment-546454106)_

**Comment by Ephellon** [comment]
@NicoLeOca, could you send me some examples please? I'll check and see if the problem still exists.

**Comment by Ephellon** [comment]
As for the deletion, yes, Firefox is designed to do that. If you want the extension permanetly, install the [Firefox Extension (XPI)](/SpaceK33z/web-to-plex/releases/download/v4.0-120214112019/moz.xpi) (will be updated soon, I'll change the link).

**Comment by NicoLeOca** [comment]
Hi @Ephellon 
Firefox (public version) doesn't allow the installation of not-signed extension.

So I installed chrome, but the extension gets many errors there.
I am pretty stuck

**Comment by Ephellon** [comment]
Hi, sorry, just woke up. Could you give me more information please?

**Comment by Ephellon** [comment]
For Firefox ([cite](https://extensionworkshop.com/documentation/publish/signing-and-distribution-overview/#distributing-your-addon), and [cite](https://extensionworkshop.com/documentation/publish/submitting-an-add-on/)), it seems I just need to uncomment the `update_url`.

**Comment by NicoLeOca** [comment]
@Ephellon 
Please have a look here.
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by Ephellon** [comment]
> @NicoLeOca, could you send me some examples please? I'll check and see if the problem still exists.

**Comment by NicoLeOca** [comment]
@Ephellon 
i'd like to but, as said earlier, I can't install the extension anymore

**Comment by Ephellon** [comment]
Yes, please see the master branch and choose the .XPI or .CRX file (or .ZIP), and follow the installation instructions (wiki)

**Comment by Ephellon** [comment]
https://github.com/SpaceK33z/web-to-plex/wiki/Installation-Guide

**Comment by NicoLeOca** [comment]
@Ephellon 
exactly what I did

**Online (CRX/XPI/JAR) — Stable/BETA**
when I click on XPI (for Firefox of course), I get the chance to download the file, but I am not offered to install it.
With Chrome I can open the CRX, only download too.

**Online (ZIP) — Stable/BETA**
I get a popup from Firefox says that I can't install this module because it has not been verified
With chrome, it says that it can't load the extension icon.

**Comment by Ephellon** [comment]
Ok, I'll check on it when I get home

**Comment by Ephellon** [comment]
I'll resign the extensions... maybe an hour or so?

**Comment by NicoLeOca** [comment]
anytime

**Comment by Ephellon** [comment]
Sorry, was in a queue for signing... try [here](https://addons.mozilla.org/en-US/firefox/addon/web-2-plex/)

**Comment by NicoLeOca** [comment]
Thanks @Ephellon 
Extension installed.
However, I could not get it to work properly

It's connected to Plex.
The connection to Radarr seems to be working but I can't switch it on.

Also, either when I go to trakt or to Allocine, on a movies that I am supposed to have in Plex, the colored dot of the extension remain red.
What is this dot supposed to display?

**Comment by Ephellon** [comment]
Red means an error occurred. Let me check on it again

**Comment by NicoLeOca** [comment]
take your time I get off to bed

**Comment by Ephellon** [comment]
OK, will resign... Will push in a few

**Comment by Ephellon** [comment]
Ah. There are multiple elements of the same information... Fixing it now

**Comment by Ephellon** [comment]
Got it. Pushing, again.

**Comment by NicoLeOca** [comment]
it is working now on trakt but not on allociné (the dot is red)
I am not sure where the issue is

**Comment by Ephellon** [comment]
Send me the URL, I'll check on it

**Comment by Ephellon** [comment]
Also, what settings do you have enabled?

**Comment by NicoLeOca** [comment]
http://www.allocine.fr/film/fichefilm_gen_cfilm=185719.html

Enabled settings are Plex, Radarr, Sonarr, Allociné and Trakt

**Comment by Ephellon** [comment]
Got the same error!

- Your settings (`firefox`): `Plex` `Radarr` `Sonarr` `Alocine` and `Trakt`
- My settings (`firefox`): *same settings*

**Comment by Ephellon** [comment]
Found the error (Searching Error): `⊘ No information was found for "Bohemian Rhapsody (2018)"`

![image](https://user-images.githubusercontent.com/8632548/70847951-fd45f680-1e27-11ea-953e-63a348ab8829.png)

**Comment by Ephellon** [comment]
It's just the film itself (TMDb says it doesn't exist). I tried "Yesterday" and it passed:

# Bohemian Rhapsody
![image](https://user-images.githubusercontent.com/8632548/70847996-a856b000-1e28-11ea-83c8-f6c7e1592030.png)

# Yesterday
![image](https://user-images.githubusercontent.com/8632548/70848002-b3a9db80-1e28-11ea-881c-0e8662f18efa.png)

**Comment by Ephellon** [comment]
Found the error! `.../3/search/{ APIType <"movie" | "tv"> }` but was using `.../film`

**Comment by Ephellon** [comment]
Temporary fix (until next push): enable `Manager Searching` (__Other Settings | Search Settings__)

**Comment by NicoLeOca** [comment]
Hi @Ephellon 
The proposed fix doesn't change anything, I still get the red dot

**Comment by Ephellon** [comment]
Noted

**Comment by Ephellon** [comment]
I'll update just the Firefox add-on with the suspected fix, give me 10min

**Comment by Ephellon** [comment]
Pushed... Waiting in queue (6 of 6)

**Comment by Ephellon** [comment]
Signed. Please update and try the suspected fix: [Web 2 Plex](https://addons.mozilla.org/en-US/firefox/addon/web-2-plex/)

**Comment by NicoLeOca** [comment]
working! 👍 
thanks for your active support

**Comment by Ephellon** [comment]
Glad to hear. Don't hesitate to send more issues! Thanks for the help 🤠

**Comment by NicoLeOca** [comment]
Hi @Ephellon 
I get a red dot with a few movies on Allocine
http://www.allocine.fr/film/fichefilm_gen_cfilm=222451.html
http://www.allocine.fr/film/fichefilm_gen_cfilm=255238.html
http://www.allocine.fr/film/fichefilm_gen_cfilm=262396.html

Do you know why?

**Comment by Ephellon** [comment]
Yes, the titles are too different:

![image](https://user-images.githubusercontent.com/8632548/71311731-593bec80-23df-11ea-86ca-60d1e82ff7ec.png)

**Comment by Ephellon** [comment]
To "fix," adjust your Loose matching settings.

----

`Strict Matching` - `false` (not exact)
`Title Matching` - `false` (not equal)
`Loose Matching` - 17% match (French v. English), 9% match (English v. French)

**Comment by Ephellon** [comment]
Be careful though, setting this to low will match false positives

**Comment by NicoLeOca** [comment]
thanks @Ephellon 
I'll stick to stick match though
In a perfect world, a nice improvement would be to have a list of possibilites to choose from ;-)

**Comment by Ephellon** [comment]
Added "Search on fail" to let the user choose a correction when Web to Plex can't find an item

> One possible correction found
![image](https://user-images.githubusercontent.com/8632548/72200975-c6560700-340c-11ea-8d43-6e303d88f11b.png)

> Multiple possible corrections found
![image](https://user-images.githubusercontent.com/8632548/72201058-657afe80-340d-11ea-9f50-b269ab51825e.png)

**Comment by NicoLeOca** [comment]
👍 
I will give it a try

**Comment by Ephellon** [comment]
I'll make a few more adjustments, might push `v4.1.1.9` later on this week
