### ISSUE TITLE
Issue: Settings won't save

### ISSUE THREAD

**Issue by ButtaJones** [SpaceK33z/web-to-plex#127]
> Use this if Web to Plex doesn't run on any page, **and** you have **Developer Mode** enabled. Please use the table below to point to the error location.

----

**Describe the error**
Settings refuse to save. Setup page keeps popping up.

**To Reproduce**
Tried logging in with token.

**Estimated location**
See screenshot.

**Screenshots**
https://i.imgur.com/cdzeuhM.jpg

**Extension Information**
 - Version: `4.1.0.22`
 - Source: `store` `GitHub`
 - Browser: `chrome`

**Comment by OmNomNomagon** [comment]
same issue. can't get any settings to stick using 4.1.0.22 on chrome. Also happens on the chrome store version. I have an older installation which still remembers settings fine. Only appears to occur on a fresh installation and configuration.

**Comment by Ephellon** [comment]
Ah, I see the problem. Also, disable the `Proxy` setting.

**Comment by Ephellon** [comment]
Fixed. Will push soon.

`throw Notification...` __must__ be `throw new Notification...`

**Comment by Ephellon** [comment]
GitHub uses keywords, closed automatically.

**Comment by Ephellon** [comment]
Please try the again. Let me know if you have any issues.

**Comment by ButtaJones** [comment]
@Ephellon I tried. This is what happened with I tried with token.
https://i.imgur.com/voeuyeW.jpg
https://i.imgur.com/aGGlnjL.jpg
https://i.imgur.com/sGYvZjm.png

With login/pass:
https://i.imgur.com/di3NGJT.png

**Comment by Ephellon** [comment]
Working on it.

**Comment by Ephellon** [comment]
Could you tell me what you filled out please (i.e. "Just the token")

**Comment by ButtaJones** [comment]
@Ephellon copied my Plex token from the xml file.

eg. http://X.X.X.X:32400/library/metadata/57538?checkFiles=1&includeExtras=1&includeBandwidths=1&X-Plex-Token=[MYTOKENHERE]

I also tried with my Plex username and password. Regular username, not thru Google. Which gave me the 2nd error about the cookies.

**Comment by Ephellon** [comment]
I recreated the error, thank you! Found the problem, should be `if(ProxyURL && ...)`, but was only `if(...)`

**Comment by Ephellon** [comment]
Pushing changes, should take 10mins

**Comment by Ephellon** [comment]
All done

**Comment by ButtaJones** [comment]
@Ephellon works. You are the G.O.A.T. my friend.

**Comment by Ephellon** [comment]
LOL, thanks. Let me know if anything else is broken

**Comment by ButtaJones** [comment]
@Ephellon I found something that should be tweaked/fixed. Open another issue?

**Comment by Ephellon** [comment]
Yes

**Comment by Ephellon** [comment]
Hey @ButtaJones, haven't noticed any new issues from you. Is there still an issue you'd like to report?
