### ISSUE TITLE
Add support for TV shows

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/web-to-plex#14]
This extension was initially meant for Movieo, which supports only movies, but now that IMDb and Trakt.tv are supported we could support TV shows as well.

**Comment by OmgImAlexis** [comment]
If you want to add support for sickbeard, sickrage or medusa all which are forks of each other there's a decent api for it. I'm one of the developers so let me know if you need any help.

**Comment by SpaceK33z** [comment]
Thanks for reaching out. For this ticket I'll first implement support for viewing TV shows from {IMDb,Trakt} in Plex, and later I'll look at implementing downloaders. I'm using Sonarr though, so I don't know if I'll ever add support for SickRage to be honest.

**Comment by OmgImAlexis** [comment]
Well if you can layout a modular system I'd be happy to add sickbeard and the two forks.

**Comment by SpaceK33z** [comment]
Alrighty, I'll ping you when it comes to that.

Unfortunately TV show download support is a lot harder than movies since there are seasons, and then you need to provide a UI in the website to select the season. Or maybe I could make an option in the settings page where you can select what it should download (e.g. `First season`, `All seasons`), that way I don't have to make a UI and it keeps everything simple. What do you think?

**Comment by OmgImAlexis** [comment]
Since sickbeard, sickrage and medusa all support thetvdb mapping it shouldn't be too hard to get it to download. You'd just need to provide the TVDB ID as well as the season and episode you want. It could then check if you've got it downloaded and if not then add the episode to the queue to download.

Trakt also displays the TVDB ID for most shows on the page so you can use that to get the ID.

**Comment by enchained** [comment]
If you will support TV shows and Sonarr in the future, I would love to have support for the myshows.me website (Russian Trakt.tv alternative for TV shows). For example: https://en.myshows.me/view/5713/
Shows pages can have urls in those formats:
```
https://en.myshows.me/view/5713/
https://myshows.me/view/5713/
https://ua.myshows.me/view/5713/
```
and every show page has an **IMDB** link, located here:
```
$("div.clear>p:nth-child(9)>a")[0].href
```
**Name**:
for pages 'https://myshows.me/ *': `$("p.subHeader")[0].innerText`
for pages 'https://**.myshows.me/ *': `$("main>h1")[0].innerText` (needs to remove extra space at the end of the result)

**Year** (needs regex for first 4-letter number):
```
$("div.clear>p.flat")[0].innerText
```

If this data is enough for the website support, I'll try to make a pull request if/when the TV support has been added.

**Comment by SpaceK33z** [comment]
I don't have the time to implement TV show support in the near future unfortunately. TV shows is a lot harder than movies because you have seasons and individual episodes, and without at least supporting seasons it's kinda useless. I imagine you would have a button on TV show pages that works like adding a show to Sonarr does:

![screen shot 2018-01-11 at 21 04 21](https://user-images.githubusercontent.com/533616/34844821-04ab3cc0-f713-11e7-927d-3595381e81b9.png)


If someone wants to start working on this I will review a PR and help anyone with it though!

**Comment by Ephellon** [comment]
Just leaving notes:

- Ignore season options, just leave a pop-up that'll take the user to the page for editing (if wanted)
- Find some sort of API documentation for SickRage

**Comment by Ephellon** [comment]
So, got everything except "adding" to work. Will keep at it for a little while

**Comment by Ephellon** [comment]
Done

**Comment by Ephellon** [comment]
~~Will not be adding SickRage support, no patience to install another application and fumble through the API~~

**Comment by Ephellon** [comment]
Why do I do this to myself? Will add to Wiki after `v4.1.3.0` goes live &rarr;

# Adding a custom manager (Experimental Feature &mdash; `v4.1.3.0`)

> Step 1: Go to "Custom Managers" under "Manager Settings"
> ![image](https://user-images.githubusercontent.com/8632548/75208638-8a1b0380-5739-11ea-8194-986b0d5a8f28.png)

> Step 2: Select "+ Add Custom Manager"
> ![image](https://user-images.githubusercontent.com/8632548/75208696-a5860e80-5739-11ea-9c5e-7f4113778ed8.png)

----

# Adding SiCKRAGE

> Step 1: Add SiCKRAGE
> ![image](https://user-images.githubusercontent.com/8632548/75208754-cfd7cc00-5739-11ea-84b6-bb0258605f5f.png)

> Step 2: Edit/verify the Connection Settings
> ![image](https://user-images.githubusercontent.com/8632548/75209150-cef36a00-573a-11ea-979c-40ba34d6bdee.png)

> Step 3: Edit/verify the Syntaxes
> ![image](https://user-images.githubusercontent.com/8632548/75208998-60aea780-573a-11ea-8f4a-8e5b456d8eaa.png)

**Comment by Ephellon** [comment]
**Things to add**

- [x] The "Import Rules" function
- [ ] The "Manager Rules Notation" functionality

> `SiCKRAGE.json`
```JSON
{
    "SiCKRAGE": {
        "type": "show",
        "api-url": {
            "GET": "{url}home/",
            "add": { "POST": "{api-url}addShows/newShow?apikey={api}&search_string={name}" },
            "find": { "GET": "{api-url}displayShow?apikey={api}&show={tvdb}" },
            "view": { "OPEN": "{:add}" }
        }
    }
}

```

**Comment by Ephellon** [comment]
Moved to #166
