### ISSUE TITLE
First time use of this plugin - Errors when trying to configure

### ISSUE THREAD

**Issue by 4C3T** [SpaceK33z/web-to-plex#154]
Hi. Just installed this plugin, on a whim, as I thought it'd be really nice to have this feature.
But, problems arose quickly after installing it.
I can't save the settings for either of the service providers (Have Plex, CouchPotato and Radarr).
If I try to enter the Login creds for Plex and hit the Login-button, the Save-button get's disabled.
If I instead go ahead and fill out any/all of the other fields and try to hit the Save-button it tells me "Select a server first".

Perhaps this has something to with the version of Firefox that I'm using, v72.0.2 (64-bit)?

I'm wondering is there's a fix for this, or perhaps a workaround like an XML-file or something where I can input my creds?
Thank you.

**Comment by 4C3T** [comment]
Ok... So, I figured it out. Turns out that I didn't have Plex Media Server installed, apparently (?), so after some configuration the settings changed and added a "Plex token" after I clicked on Login.
Now I can add other media services,
Perhaps it could be a mentioning of criteria on the plugin settings page for this...
I almost gave up on this plugin, a hair away I might add!

**Comment by Ephellon** [comment]
Good morning (2A) just saw this 😬 I'll be sure to add the criteria to the settings' page as well, thank you 🙂

**Comment by Ephellon** [comment]
I'll also remove Plex (completed) as a requirement, i.e. if Plex fails to load properly, ignore it

**Comment by Ephellon** [comment]
😒 note to self, notifications don't work for FastHub

**Comment by 4C3T** [comment]
Btw, the plugin haven't worked while being on imdb since I made the changes for some reason. I haven't tried it much to be honest (Been busy with other stuff).
I only got a popup before when it wasn't configured properly, and I think I saw a button on the right hand middle or near the bottom once after that, but it might have been before.
Also, the addon has been removed from Firefox Addons and I think I searched for it or if it was from Plex I got it. I don't remember.

What version is the right one?
I currently have version 3.4 installed

Here's another from not quite remembering what I did, but I added a shortcut containing a java-script to add to CouchPotato. It was from one of the numerous sites I was bouncing around installing Plex, Plex server, CouchPotato and whatnot. Was that one yours as well?

**Comment by 4C3T** [comment]
And another thing while I'm at it.
Would be nice to have a test-button for CouchPotato in the settings as well so that one can confirm that it's authenticating properly, and thus working...

**Comment by Ephellon** [comment]
1. The most current version is `v4.1.1.11` (please use [this link](https://addons.mozilla.org/en-US/firefox/addon/web-2-plex/) to Mozilla Add-ons)
    * Please note, Web to Plex ("Web 2 Plex" `v4.1`) can **not** be searched for in Mozilla Add-ons. All links are provided in the [README](https://github.com/SpaceK33z/web-to-plex)
2. CouchPotato's login status isn't testable (yet)

> Your installation should look similar to this:
> ![image](https://user-images.githubusercontent.com/8632548/73892293-c4c50680-4833-11ea-9f47-4c3b278c2377.png)
