### ISSUE TITLE
Issue: Ombi doesn't work

### ISSUE THREAD

**Issue by PotatoQuality** [SpaceK33z/web-to-plex#161]
> Use this if Web to Plex doesn't run on any page, **and** you have **Developer Mode** enabled. Please use the table below to point to the error location.

----

**Describe the error**
When i try to push a request to ombi, a error occurred everytime 

**To Reproduce**
1. Go to (for example) https://trakt.tv/shows/fbi
2. Click on add tv show in web to plex
4. Request is sending
5. getting error 
![error](https://user-images.githubusercontent.com/2944704/74596923-354efd00-5056-11ea-8547-653206307ad8.png)

**Estimated location**
Use the [fail locator](https://github.com/SpaceK33z/web-to-plex/wiki/Fail-Location-(Bug-Creator)) to establish where the error is. Can also be found in the Extension manager's error reports.
utils.js:2012

**Screenshots**
![error](https://user-images.githubusercontent.com/2944704/74596923-354efd00-5056-11ea-8547-653206307ad8.png)

**Extension Information**
 - Version: `4.1.1.9`
 - Source: `store`
 - Browser: `chrome`

**Additional comments**
Add any other comments about the problem here, such as how often the issue occurs, any new changes, etc.

error in console:

```
utils.js:2012 Error adding to Ombi: SyntaxError: Unexpected end of JSON input @0B: Push_Ombi => fetch(<IP Address>, { headers }).catch(error => { sendResponse }) {headers: {…}, request: {…}, url: <IP Address>}
(anonymous) @ utils.js:2012
```
error in ombi:

```
fail: Ombi.Api.Api[1000]
      StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://api.tvmaze.com/lookup/shows?thetvdb=0
fail: Ombi.ErrorHandlingMiddleware[0]
      Something bad happened, ErrorMiddleware caught this
System.ArgumentNullException: Value cannot be null.
```

**Comment by Ephellon** [comment]
Hi. For "error in ombi," it says the ID is `0`, may I ask what show you were trying to add?

**Comment by Ephellon** [comment]
And site*

**Comment by Ephellon** [comment]
Found the problems, the `apikey` needs to appended to the URL

**Comment by Ephellon** [comment]
Alright, getting ready to push the updated version. Running a few more tests

**Comment by PotatoQuality** [comment]
Thanks for the quick response and investigation! :)

**Comment by Ephellon** [comment]
No problem :) just need to fix CouchPotato again

**Comment by Ephellon** [comment]
Pushing [`v4.1.2.3`](https://github.com/SpaceK33z/web-to-plex/releases/tag/v4.1.2.3-1800MST19FEB2020)

**Comment by Ephellon** [comment]
Still failing, will redo

**Comment by Ephellon** [comment]
Ah, added it correctly, but not in all needed spots
