### ISSUE TITLE
Additional sources

### ISSUE THREAD

**Issue by mofman** [SpaceK33z/web-to-plex#17]
Absolutely love this plugin I thought of a few more places where we could add buttons.

- [x] Google search results page movie widget
  - Ephellon: Will review @mofman's PR #20
  - Ephellon: Also review SpaceK33z@db59b00118a0e309766f13e9ae15ada95ecdbdc2
  - Ephellon: Won't require too many changes, mostly commentation and debugging text
- [x] Letterboxd list page (allows you to download all movies in list with one click)
  - Ephellon: In progress, **not** very feasible
  - Ephellon: No IMDb IDs given, may cause bandwidth issues if requests aren't queued and cached
- [x] IMDB's list page (allows you to download all movies in list with one click)
  - Ephellon: In progress, feasible
  - Ephellon: IMDb has very subtle ways of defining movies v. TV series
  - Ephellon: The different list views give different anchor parents
  - Ephellon: Adapt SpaceK33z@660c840219a726ab385f0b38070f27f55c2124ac
    - Item anchors: `#main [class*="item"][class*="content"] a[href*="/title/tt"]:not([href*="/showtimes/"])`
    - Item title: `Item.innerText`
    - Item year: `Item.nextElementSibling()`
- [x] Letterboxd
- [x] Rottentomatos
- [x] Metacritic

**Comment by SpaceK33z** [comment]
Thanks!

For the Google search results, perhaps place a button here?

![2016-12-21_22-53-34](https://cloud.githubusercontent.com/assets/533616/21407352/5d0c116e-c7d0-11e6-9723-3ad2669fbee2.png)

Would you be interested in doing a PR for some of those places? I'll start working on the IMDB list page one soon.

**Comment by mofman** [comment]
Yes I think that one on google would pretty useful.

Yes I'll do a PR over christmas for some of these sites.

**Comment by SpaceK33z** [comment]
@mofman, I added the Plex button for IMDb list pages.

Also I researched a bit about the other sources. To find media on Plex / CouchPotato, a IMDb ID, title and year of the movie/TV show needs to be available on the page.

- Letterboxd fulfills these requirements.
- Rottentomatoes doesn't have an IMDb id.
- Google search results fullfils these requirements.
- Metacritic doesn't have an IMDb id.

**Comment by mofman** [comment]
Nice work - I've added it googles widget and also letterboxd - strangely letterboxd doesnt seem to find the movie on plex even though the xhr request is right, anything you can think I'm doing wrong?

**Comment by SpaceK33z** [comment]
No idea out the top of my head. If you send the pull request, I'll help you debug it.

**Comment by mofman** [comment]
@SpaceK33z cheers! https://github.com/SpaceK33z/web-to-plex/pull/20

**Comment by petersw730** [comment]
Thanks for this great extension!  Any progress on adding support for Letterboxd?

**Comment by SpaceK33z** [comment]
Letterboxd support has been added! v3.2 has just been released, it may take a few hours before your browser auto-updates. Thanks to @mofman.

**Comment by Ephellon** [comment]
Implemented in v4.
