### ISSUE TITLE
Not working in Firefox Developer Edition

### ISSUE THREAD

**Issue by MartinAyla** [SpaceK33z/web-to-plex#19]
Thanks for a great extension!

It doesn't seem to work in the latest Firefox Developer Edition though.

It doesn't seem to save the settings. If I input my Plex Token, close the preferences, and open them again, it hasn't been saved.

I'm using Firefox on macOS:
52.0a2 (2016-12-23) (64-bit)

**Comment by SpaceK33z** [comment]
Thanks for your bug report. This extension tries to use the sync API for options if possible, so your options are synced across devices. Firefox < 52 didn't support this, but now it suddenly does. However, when using the sync API it throws this error:

```
Unchecked lastError value: Error: Please set webextensions.storage.sync.enabled to true in about:config
```

So you still need to manually set a flag for this, which means it's unusable. This is very inconsistent with Chrome, which automatically falls back to local storage if you didn't enable sync storage.

Anyway, it's been fixed now.

**Comment by MartinAyla** [comment]
Thanks a lot for the quick help, happy holidays.
