### ISSUE TITLE
Remove debugging from production version

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/web-to-plex#21]
The person who reviewed the FF add-on said this:

> 1) Your add-on's code includes instances of printing debugging information to the Console, which is generally not allowed in production add-ons. Please remove or disable such logging. 

I do want to keep this debugging information because it saves time debugging, but perhaps I can find a way to not include it in the production version.

**Comment by Ephellon** [comment]
Make a global variable for `console`, e.g.

## Debugging
```javascript
var terminal = console;
// ...
terminal.log("Plugin breaks here");
```

## Production
```javascript
var terminal = {
    log: m => m,
    error: m => m,
    warn: m => m
};
// ...
terminal.log("Plugin breaks here"); // still valid
```
