### ISSUE TITLE
Can't save settings in Chrome

### ISSUE THREAD

**Issue by MartinAyla** [SpaceK33z/web-to-plex#26]
Hi

Thanks for a great extension, I really want to try it!

I'm using v2.3 in Chrome version 55.0.2883.95 (64-bit) on macOS.

I can't save the extension settings, nothing happens when I click the "save" button and settings aren't remembered.

Any ideas?

**Comment by SpaceK33z** [comment]
To be sure, you did select a Plex server first? And is they "Save" button not greyed out?

Could you try to open the DevTools (hit F12, or cmd+alt+i), click on the "Console" tab, open the Options page, hit save after selecting a Plex server and make a screenshot of what you see in the DevTools?

**Comment by MartinAyla** [comment]
Thanks for the quick help!

Yes, I selected my Plex server and "Save" is not greyed out.

There's not much in the Console, it only says this:
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

<img width="1431" alt="screen shot 2017-01-03 at 13 08 40" src="https://cloud.githubusercontent.com/assets/3063746/21607349/ce50f68e-d1b5-11e6-9921-a6aee1a73ef2.png">

**Comment by MartinAyla** [comment]
I've tried restarting Chrome and disabling some extensions but I just can't click that "Save" button, it just gets a blue outline. Do you have any other ideas I can try?

Thanks a lot

**Comment by SpaceK33z** [comment]
That warning in the console seems to be unrelated. Weird, after clicking save it should at least say "Options saved." next to the save button. 

I've added some extra logging on the options page. Could you do this:

1. uninstall the extension
2. `git clone` this repository
3. Go to `chrome://extensions/`
4. Click "Developer mode" (see screenshot)
5. Click "Load unpacked extension" (see screenshot)
![2017-01-04_11-30-27](https://cloud.githubusercontent.com/assets/533616/21639614/41547e06-d271-11e6-8426-85d5d23e41e7.png)
6. Then go to the directory of the repository and choose the `src/` directory.
7. The extension should be installed from source now.
8. Open the DevTools again.
9. Go to Options and try again what happens.

**Comment by MartinAyla** [comment]
Sorry @SpaceK33z - I found the extension that broke the Save button in your extension.

I disabled SurfingKeys (a Vim extension) and I could click on Save.

Sorry to have troubled you with this and thanks a lot for the help!

**Comment by SpaceK33z** [comment]
Oh no problem! Interesting that it can break the options page in this way, I'll leave this open so I can take a look at it.
