### ISSUE TITLE
Can't save config to the right server

### ISSUE THREAD

**Issue by RDDJ** [SpaceK33z/web-to-plex#27]
Hey, I have three PLEX servers, which all show up in the extensions options, but my main server is the middle server shown in the list, but i only seem to be able to test and save when choosing the top server in the list. If i choose the second or third servers, it just reverts back to the top option.

**Comment by SpaceK33z** [comment]
Could you check the Console in the development tools? I've recorded how to do this:

![kapture 2017-01-20 at 12 35 48](https://cloud.githubusercontent.com/assets/533616/22148201/02810b88-df0d-11e6-95cd-20be7f31d587.gif)

I'm interested in the contents of the "Console" tab. Note that it's important that you right-click IN the options popup. Thanks!

**Comment by SpaceK33z** [comment]
btw, are you using Chrome or Firefox?
