### ISSUE TITLE
Add support for Radarr?

### ISSUE THREAD

**Issue by MartinAyla** [SpaceK33z/web-to-plex#28]
I would love to see support for Radarr (CouchPotato alternative).

Development is really taking off (and they have torrent support, which the dev mentioned was missing from Watcher).

Thanks :)

**Comment by SpaceK33z** [comment]
Yeah sure. Can take a while before I have time for this, so feel free to work on it.

Could you find out for me if their API offers a way to add a movie based on a IMDb ID?

**Comment by MartinAyla** [comment]
Sounds great!

I have asked the Radarr folks here:
https://github.com/Radarr/Radarr/issues/194

**Comment by MartinAyla** [comment]
They answered already, that: "It requires TheMovieDbId"

**Comment by SpaceK33z** [comment]
Okay, thanks. Some websites provide that id already, but for the ones that don't provide it, it will be a lot more difficult. We'll need to find an open API that converts IMDb ID to a TMDB id. The TMDB has an API, but it requires you to sign up. I'm not sure if they allow it if the secret key is visible.

**Comment by MartinAyla** [comment]
Thanks for looking in to this SpaceK33z :) Both Watcher and Radarr supports torrents now. I hope for support for both (although it seems that Radarr has the fastest development effort right now).

**Comment by inonprince** [comment]
I've added radarr and PassThePopcorn support to my fork of web-to-plex
https://github.com/inonprince/web-to-plex

**Comment by SpaceK33z** [comment]
@inonprince woah awesome. Would you be interested in making a PR to this repository with the Radarr / PTP support added? Only small problem is that you removed Couchpotato support in your fork; I'd still like to support both.

**Comment by SpaceK33z** [comment]
Hey, it's been more than a year but I have finally implemented Radarr support 😄. I will be releasing a new version soon.
