### ISSUE TITLE
Cannot read property 'Hub' of undefined

### ISSUE THREAD

**Issue by AlexSTV** [SpaceK33z/web-to-plex#29]
Hey, I'm running into an issue with the plugin reading results from the Plex API. I am using Chrome - Windows 7, Plex version 1.2.7.2987.

Here is the error I'm getting in the Chrome console: ![image](https://cloud.githubusercontent.com/assets/5434285/22029225/ca51f700-dcd1-11e6-902d-8e9709375928.png)

I can run the fetch request manually and Plex returns valid JSON: [example](https://gist.github.com/AlexSTV/5798c9c75676df1ec19f26bb72f0aca6)

But this does not look like the data structure [utils.js line 27](https://github.com/SpaceK33z/web-to-plex/blob/db59b00118a0e309766f13e9ae15ada95ecdbdc2/src/utils.js#L27) is expecting. Since 'data.MediaContainer.Hub' tries to read data's Media container property which does not exist it throws the 'Cannot read property 'Hub' of undefined' error. Maybe there was a change in the Plex api or I could an old version.

I'd be happy to add you to my Plex server @SpaceK33z if you want to try replicating it that way. Otherwise I can also post any logs or info you need.

Thank you for your time and thanks so much for creating this plugin, once I get it running I think it will make Movieo even better for discovering movies to watch!

**Comment by SpaceK33z** [comment]
Thanks! Could you try updating to the latest Plex Media Server?

**Comment by AlexSTV** [comment]
Updating to Plex version 1.3.3.3148 fixed the issue. That should have been the first thing I tried, thanks for your time!

![image](https://cloud.githubusercontent.com/assets/5434285/22039835/bb36bb44-dcf8-11e6-8226-95db08fa28ca.png)

**Comment by SpaceK33z** [comment]
Don't worry, I really should make some kind of warning. I'll edit the README and add it to the Chrome webstore description.
