### ISSUE TITLE
Unable to save options?

### ISSUE THREAD

**Issue by benbar21** [SpaceK33z/web-to-plex#30]
Hey,

I'm not sure exactly which details you want but I'm running windows 10 and using the latest version of chrome (Version 55.0.2883.87 m (64-bit)).

When I try to configure web to plex it finds my server, but when I hit save nothing happens. If I open options again nothing has been saved, and when I go to any compatible site it tells me to configure the app.

Any ideas?

Thanks!

**Comment by SpaceK33z** [comment]
Could you check the Console in the development tools? I've recorded how to do this:

![kapture 2017-01-20 at 12 35 48](https://cloud.githubusercontent.com/assets/533616/22148201/02810b88-df0d-11e6-95cd-20be7f31d587.gif)

I'm interested in the contents of the "Console" tab. Note that it's important that you right-click IN the options popup. Thanks!

**Comment by benbar21** [comment]
Yep, when I hit save I get this:

`

    index.js:33 Uncaught TypeError: Cannot read property '0' of undefined
    at getBestConnectionUrl (index.js:33)
    at HTMLButtonElement.saveOptions (index.js:78)
`

**Comment by SpaceK33z** [comment]
Thanks, I've fixed the issue in 71e059fc0a05ad9f202232651755b00b8d967278 and will publish a new version soon.

However, this should only appear if your Plex server is available only locally. Can you confirm that is the case? If this is not the case, I'm curious what PMS version you're running.

**Comment by benbar21** [comment]
Great

My setup is not a common one, I suppose. My plex server is proxied through a secured NGINX server and then access via Cloudflare. I then have the Cloudflare address listed a s a custom server access URL.

It works remotely 100%, in that I can access it from plex.tv, apps, iptvs, and so on. However, my plex server itself doesn't seem to recognize the custom access URL and so it believes that the server cannot be accessed remotely.

If I didn't explain it properly I can try to explain it better if you want.

Thanks again for fixing it!

**Comment by SpaceK33z** [comment]
Aha okay, that explains a lot. It will mean though that, after this fix has been published, you can only use it when you are in the same network.

**Comment by SpaceK33z** [comment]
I just released `2.4`, you should get an auto-update soon. Let me know if it doesn't work!
