### ISSUE TITLE
ERROR: You must be lost. This page doesn't exist.

### ISSUE THREAD

**Issue by Crunch1969** [SpaceK33z/web-to-plex#33]
When I click "On Plex" button on imbd.com I get a page saying "You must be lost. This page doesn't exist."

The link on the error page ends with:  
/details/%2Flibrary%2Fmetadata%2F255

But the link on the actual movie page it was supposed to show ends with:
/details?key=%2Flibrary%2Fmetadata%2F255

**Comment by SpaceK33z** [comment]
Are you running the latest version of Plex Media Server? I can't reproduce this error.

**Comment by Crunch1969** [comment]
Yes, I am running version 1.9.5.4339

**Comment by SpaceK33z** [comment]
Do you happen to use web-to-plex on FireFox? In the latest version of this extension, 2.5, I fixed the Plex movie page url (since it changed recently), but I see now that I haven't updated the Firefox addon yet; it's still on 2.3.

**Comment by Crunch1969** [comment]
Yes, that must be it. I am using it on Firefox. When will you be updating it?

// Øyvind

**Comment by SpaceK33z** [comment]
Done, you should get v2.5 automatically :). Let me know if you still have issues.
