### ISSUE TITLE
Plex Error

### ISSUE THREAD

**Issue by frilleee** [SpaceK33z/web-to-plex#34]
So i found this Extension and wanted to test it but i got the Plex Error like this guy got 
https://github.com/SpaceK33z/web-to-plex/issues/22
but as they say at the end of the thread they know what the problem is and its same for me :)
but now im not super good at coding but know the basic 
where do i change the adress for the plex so it doesent use my external ip and use my local ip cose i have my plex server on my computer
and that should fix the problem?

also if i use a vpn the Extension works

**Comment by tejapoth** [comment]
Hi even Im facing the same issue. Pls fix.

**Comment by alexpclarke** [comment]
as am I

**Comment by SpaceK33z** [comment]
I was able to reproduce the same error and I think it's been fixed. I'll release a new version shortly. Do note that "Plex Error" is a very generic error so it might not have been fixed in your case.

**Comment by maxcore** [comment]
same bug for me with the version 3.0

**Comment by lastb0isct** [comment]
Getting the following error:  Mixed Content: The page at 'https://www.imdb.com/title/tt0109830/?ref_=nv_sr_1' was loaded over HTTPS, but requested an insecure resource 'http://PLEXIPADDRESS/hubs/search?query=title:Forrest%20Gump'. This request has been blocked; the content must be served over HTTPS.
