### ISSUE TITLE
Matching needs to be more robust

### ISSUE THREAD

**Issue by InStim** [SpaceK33z/web-to-plex#38]
Title matching matches titles that aren't the movie but have shared text.

Visited "The Greatest Showman" on IMDB. https://www.imdb.com/title/tt1485796/

Extension adds an "On Plex" button to the page. That movie is not in our library. Click the On Plex button and get taken to "The Greatest Showman - Never Enough [Official Lyric Video]" that has been downloaded and in a local Music Videos library. 

There are actually four music videos on the server with "The Greatest Showman" in the title. "The Greatest Showman - Never Enough [Official Lyric Video]" is neither the first nor last alphabetically or by date added. Unsure why that was the title was chosen to link to on the Plex server.

**Comment by SpaceK33z** [comment]
Hmm this will be hard to fix reliably. It already scopes the search of titles on a specific library type, so e.g. a library with the type "Other Videos" will not be searched. Are you using the library type "Movies" on purpose for music videos?

**Comment by InStim** [comment]
Our Music Videos library is Type Other Videos not Movies. Scanner Plex Video Files Scanner, and Agent Personal Media.

**Comment by SpaceK33z** [comment]
Please test v3.3 (your browser should auto-update soon)!
