### ISSUE TITLE
CouchPotato request failed (look in DevTools for more info)

### ISSUE THREAD

**Issue by chierichetto** [SpaceK33z/web-to-plex#41]
Set up with local IP, api-key and username and password in options.

![screen shot 2018-03-14 at 17 41 01](https://user-images.githubusercontent.com/18458417/37416757-f24f8d3e-27ae-11e8-8d82-ebe03f77a8ea.png)

**Comment by SpaceK33z** [comment]
I think this is fixed with PR #40, so this will be in the next release (you can expect a release tonight).

**Comment by chierichetto** [comment]
Okay, thanks!

**Comment by SpaceK33z** [comment]
v3.1 is released and it should auto-update automatically for you shortly. Please let me know if you still have issues.
