### ISSUE TITLE
PLEX ERROR

### ISSUE THREAD

**Issue by GugZi** [SpaceK33z/web-to-plex#42]
i am getting this error

<details>
<summary>Trakt</summary>
<ul>
<li>Request to Plex failed TypeError: Failed to fetch utils.js:305</>

-     ---------                                                            ----------
	getPlexMediaRequest.then.catch.err 		@ utils.js:305
	Promise.catch (async)
	findPlexMedia 					@ utils.js:299
	initPlexThingy 					@ trakt.js:72
	wait 						@ trakt.js:35
	wait 						@ utils.js:5
	init 						@ trakt.js:32
	parseOptions.then 				@ trakt.js:78
	Promise.then (async)
	(anonymous) 					@ trakt.js:75
</details>

<br>

<details>
<summary>imdb</summary>
<ul>
<li>Request to Plex failed TypeError: Failed to fetch</li>

-     ---------                                                            ----------
    getPlexMediaRequest.then.catch.err		        @utils.js:305
	Promise.catch (async)
	findPlexMedia						@ utils.js:299
	initPlexMovie						@ imdb.js:56
	parseOptions.then					@ imdb.js:108
	Promise.then (async)
	(anonymous)						@ imdb.js:106
</details>

<br>

chrome lastest version
plex lastest version

**Comment by SpaceK33z** [comment]
Sorry but this is not enough information for me. Can you try the latest v3.2? It has just been released so it may take some hours before your browser updates to v3.2. Be sure to go to the options page and save the settings again.

**Comment by GugZi** [comment]
i do have 3.2 now. but now i just got

utils.js:293 Request to Plex failed TypeError: Failed to fetch
  | getPlexMediaRequest.then.catch.err | @ | utils.js:293

**Comment by SpaceK33z** [comment]
In the options, can you right-click in the modal, like in the screenshot, then press the "Test" plex button and then hit Save? You should see some info in the console, something like "Chosen Plex Server URL". What is the URL you see next to that? Since it is kinda private data feel free to modify characters.
![screen shot 2018-03-18 at 14 18 12](https://user-images.githubusercontent.com/533616/37566279-4417ab5a-2ab7-11e8-8008-7a996ed2ee42.png)

Also on Plex Web, in the settings, do you see something like this?

![screen shot 2018-03-18 at 14 21 40](https://user-images.githubusercontent.com/533616/37566323-bc03c73e-2ab7-11e8-94a9-e402146a6dce.png)

**Comment by GugZi** [comment]
i see it select my public ip, and i don't have nat in my router and i can activate it. so is der a workaround?

`Currently selected server information {"Connection":[{"protocol":"https","address":"192.168.87.XXX","port":"32400","uri":"https://192-168-87-XXX.d944930ff6114XXXXXXX.plex.direct:32400","local":"1"},{"protocol":"https","address":"95.154.XX.XXX","port":"21682","uri":"https://95-154-XX-XXX.d944930ff6114XXXXXXX.plex.direct:21682","local":"0"}],"name":"GugZi's Plex","product":"Plex Media Server","productVersion":"1.12.1.4885-1046ba85f","platform":"Windows","platformVersion":"10.0 (Build 16299)","device":"PC","clientIdentifier":"aa81f583336d35f4XXXXXXX","createdAt":"1519232094","lastSeenAt":"1521378563","provides":"server","owned":"1","accessToken":"vqDL7wXXXXXXX","publicAddress":"95.154.XX.XXX","httpsRequired":"0","synced":"0","relay":"1","publicAddressMatches":"1","presence":"1"}
index.js:161 Chosen Plex Server URL: https://95-154-17-195.d944930ff6114XXXXXXX.plex.direct:21682`

**Comment by GugZi** [comment]
ok. hope you will make the fix soon, i really like this feature

**Comment by SpaceK33z** [comment]
See https://github.com/SpaceK33z/web-to-plex/issues/22#issuecomment-374657001
