### ISSUE TITLE
Could not add to Radarr.Error:Movie Was Not Found

### ISSUE THREAD

**Issue by darrylmorley** [SpaceK33z/web-to-plex#43]
Hi,

I get this error when trying to add a movie from either IMDB or Trakt. The extension connects fine to Radarr and the movie can be found when searching via Radarr.

Thanks.

**Comment by darrylmorley** [comment]
Error with adding on Radarr: Error: Movie was not found.  utils.js:234
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

**Comment by SpaceK33z** [comment]
Could you link to the IMDB page of such a movie that is failing?

**Comment by SpaceK33z** [comment]
@darrylmorley do you still have this issue and if so can you link me to an IMDB page of a movie that fails?

**Comment by darrylmorley** [comment]
Hi, sorry I removed this as it didn't work.

Thanks.
