### ISSUE TITLE
Plex Error (firefox)

### ISSUE THREAD

**Issue by mofman** [SpaceK33z/web-to-plex#47]
When I land on imdb pages now I get a PLEX ERROR button

In the console I see the message - 

> Request to Plex failed Cannot start a race without promises!

**Comment by SpaceK33z** [comment]
Can you try going to the options page and hitting the save button there? Since v3.3 it tries to connect to all your known Plex server URLs, but that only works after saving the options.

**Comment by mofman** [comment]
Ah that seems to have fixed it - thanks!

**Comment by amaklp** [comment]
I'm getting the same console error on both FF and Chrome. I have logged in successfully in the options page and hit Save.
![plexerror](https://user-images.githubusercontent.com/16342124/44947657-4d5a9e80-ae19-11e8-883b-ab3d5d7a55bf.PNG)
