### ISSUE TITLE
Invalid Path Error

### ISSUE THREAD

**Issue by Ephellon** [SpaceK33z/web-to-plex#50]
For `Radar storage path`, what should it look like? (`/storage/Movies/` isn't helping really)

When attempting to add any movies, an error appears (verbatim): "Could not add to Radarr.Invalid Path"

**Comment by Ephellon** [comment]
Thanks. Also, the path is slash-sensitive for Windows(?)... Tried `.../Movies` (didn't work), changed to `...\Movies` and it worked.

**Comment by SpaceK33z** [comment]
Thanks, good to know. I opened #51 to set the path automatically in the future.
