### ISSUE TITLE
Firefox extension error on IMDB

### ISSUE THREAD

**Issue by aidanb** [SpaceK33z/web-to-plex#52]
Hi,
When I click Download on an IMDB page I receive the following error: CouchPotato request failed (look in DEV tools for more info).

The console shows the following error:
![image](https://user-images.githubusercontent.com/2392934/40872266-ac84a42a-664b-11e8-9291-88893c793f32.png)

**Comment by SpaceK33z** [comment]
Hi! This error means that CouchPotato returned a non-JSON response.

It does two requests; first one to check if the movie is already in CouchPotato, and then one to add it. The first request is this `[YOUR COUCHPOTATO URL]/media.get?id=[AN IMDB ID]`. Could you fill the variables in and enter that URL in your browser?

I don't use CouchPotato myself anymore so it's a bit difficult to help.

**Comment by aidanb** [comment]
[YOUR COUCHPOTATO URL]/media.get?id=[AN IMDB ID] in a browser just takes
me to the CouchPotato login page. If I login with username and password,
trying the URL again redirects to [CP URL]/couchpotato/=[IMDB ID]
without the movie being added.
(This is assuming the IMDB ID is something like this: tt5619332)


On Sat, 2 Jun 2018, at 10:33, Kees Kluskens wrote:
> Hi! This error means that CouchPotato returned a non-JSON response.> It does two requests; first one to check if the movie is already in
> CouchPotato, and then one to add it. The first request is this [YOUR
> COUCHPOTATO URL]/media.get?id=[AN IMDB ID]. Could you fill the
> variables in and enter that URL in your browser?> I don't use CouchPotato myself anymore so it's a bit difficult
> to help.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/SpaceK33z/web-to-plex/issues/52#issuecomment-394073554

**Comment by SpaceK33z** [comment]
> in a browser just takes me to the CouchPotato login page

Ah, your CP sits behind a login page. This extension does have support for basic auth (handy if you have e.g. a proxy running like Apache or Nginx), but not for CP's own login info. So you could either use basic auth instead, or maybe write a PR to implement support for CP's own login 😄. Hope that works for you!

**Comment by aidanb** [comment]
Ah ok, got it. Thanks!


On Sat, 2 Jun 2018, at 10:42, Kees Kluskens wrote:
>> in a browser just takes me to the CouchPotato login page


> Ah, your CP sits behind a login page. This extension does have support
> for basic auth (handy if you have e.g. a proxy running like Apache or
> Nginx), but not for CP's own login info. So you could either use basic
> auth instead, or maybe write a PR to implement support for CP's own
> login 😄. Hope that works for you!> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
Links:

  1. https://github.com/SpaceK33z/web-to-plex/issues/52#issuecomment-394074112
