### ISSUE TITLE
Issue: Doesn't work with Firefox

### ISSUE THREAD

**Issue by AggelosM** [SpaceK33z/web-to-plex#56]
I've installed it on Chrome and FF. On Chrome it displays correctly, on FF it doesn't appear.

**Comment by bolhaskutya** [comment]
+1

I can't save settings in Firefox. It says "`Select a server first`". Here is a screenshot.

![web-to-plex-bug](https://user-images.githubusercontent.com/34036534/49875365-200e8b00-fe21-11e8-909d-39ba38cdd3de.jpg)

**Comment by bolhaskutya** [comment]
@Ephellon 
- I may have misinterpreteded the whole thing completely. 
- I only want to use the addon to send to radarr (synology). I don't use plex at all.
- If I fill in my plex username/password used at https://plex.tv and press the login button, nothing happens, only the save button becomes greyed out.
- There isn't any server selection under plex settings.
- Where can I get the log?

Here is another screenshot.
![plex-bug](https://user-images.githubusercontent.com/34036534/49898411-451ef000-fe59-11e8-9d8b-b3bb58cd87ea.jpg)

_Any advice is appreciated._

**Comment by Ephellon** [comment]
Hi @bolhaskutya, unfortunately the extension is designed to work exclusively with Plex (it's required). I'll make a new ticket for this as an enhancement.

**Comment by davel23** [comment]
Is this plugin still under development?  I have an older version installed in Firefox, I love it and would love to be able to install the latest version.

**Comment by Ephellon** [comment]
Yes, it's still being worked on currently

**Comment by Ephellon** [comment]
Haven't forgot about this ticket, I'll read FF's API for extensions, might have to do this by hand...

**Comment by Ephellon** [comment]
Uploaded the CRX to [Mozilla's Extension Tester](https://www.extensiontest.com/test/b298d2b0-eb7d-11e9-98a2-033a861ee47f) and it says it's compatible. Could someone please test on FF? I will test it too.

![image](https://user-images.githubusercontent.com/8632548/66589322-851f3400-eb4b-11e9-83d8-4ff4e46fdfa3.png)

**Comment by Ephellon** [comment]
About to post a **FireFox ONLY** ZIP, please test this out

**Comment by Ephellon** [comment]
Or not... Can't even load the icons correctly. Will work on later

**Comment by Ephellon** [comment]
Still having issues with FF, will read up on API later<sup>?</sup>

**Comment by Ephellon** [comment]
Please try [Web to Plex (Firefox Edition).zip](https://github.com/SpaceK33z/web-to-plex/files/3747280/Web.to.Plex.Firefox.Edition.zip)

**Comment by Ephellon** [comment]
Please see the beta-branch for the Firefox (BETA) update...

**Comment by Ephellon** [comment]
Understanding the API a little better, will hopefully push a fix by 29th

**Comment by Ephellon** [comment]
"Fixed." There are still minor errors, and I'm already working on them... See the beta-branch for the update

**Comment by Ephellon** [comment]
Crashes when installing... Will check out later

**Comment by Ephellon** [comment]
Fixed<sup>?</sup> @ `background.js`

**Comment by Ephellon** [comment]
Alright, Firefox is just stupid... but got it to install properly, will push later:

[moz.zip](https://github.com/SpaceK33z/web-to-plex/files/3811671/moz.zip)

**Comment by Ephellon** [comment]
Not finding any issues (new) at the moment. Been good for 7 days.
