### ISSUE TITLE
Use the "Original Title" on IMDB to search for the movie in Plex

### ISSUE THREAD

**Issue by amaklp** [SpaceK33z/web-to-plex#57]
For instance, I've set on the [IMDB preferences ](https://www.imdb.com/preferences/general) the option _Title display country/region:_ to **United States** to see the English title of foreign movies. However, [IMDB doesn't always respect this option ](https://getsatisfaction.com/imdb/topics/the-title-display-country-language-settings-dont-work)and on some movies like _Under The Skin_ it displays the Greek title (since I'm from Greece).
![plexerror](https://user-images.githubusercontent.com/16342124/44947962-da9ff200-ae1d-11e8-8c1d-a81da0105993.PNG)

Is there any way to use the original title (which is being displayed under the Greek title) to search for the movie in Plex?

Thank you.

**Comment by Ephellon** [comment]
Update: found a much easier way of using the "original title" of the film. Making an update now.

Note: selector `.originalTitle` contains the originating country's title
