### ISSUE TITLE
Add Trakt support

### ISSUE THREAD

**Issue by OmgImAlexis** [SpaceK33z/web-to-plex#6]
I'd be great to be able to have this working with Trakt as well.

**Comment by SpaceK33z** [comment]
I agree that would be great, I imagine a lot more people use it then Movieo so it could also attract more people. Need to come up with a different name then though, any suggestions 😄 ?

Also, do you have any preference where the button would be added on a Trakt page? A screenshot/mockup would be really appreciated.

It would be relatively easy to add support for Trakt I think. Some code needs to be extracted from the Movieo content script so we can reuse huge parts.

**Comment by SpaceK33z** [comment]
Trakt.tv support is implemented now! For the moment it only works for movies (just like IMDb and Movieo), but I'll make it work for TV shows soon (see #14).

I'll release a new version very soon.
