### ISSUE TITLE
Remove Plex login requirement

### ISSUE THREAD

**Issue by Ephellon** [SpaceK33z/web-to-plex#61]
Suggested by @bolhaskutya in #56:
> I only want to use the addon to send to radarr

This would require a slight overhaul, as the code is designed to search Plex for matching media... Maybe a dummy machineID can be used, as long as they have a Plex account?

**Comment by bolhaskutya** [comment]
Ahh, I see. So you actually check for movies using plex, not just simly sending them to radarr/sonarr. I didn't realize that.

**Comment by Ephellon** [comment]
Yes. Sorry about the confusion

**Comment by Ephellon** [comment]
Done. It will cause errors for users not paying attention.

I added prompts to try and tell/deter the user from not using a server.
