### ISSUE TITLE
Possible Features (v4.1)

### ISSUE THREAD

**Issue by Ephellon** [SpaceK33z/web-to-plex#62]
> See [__SpaceK33z:beta-branch__](https://github.com/SpaceK33z/web-to-plex/tree/beta-branch) for the most current version (Chrome/Edge/Firefox/Opera)

----

Moved to [Project](https://github.com/SpaceK33z/web-to-plex/projects/4)

**Comment by matt314159** [comment]
Hey all, I LOVE this extension.  Sorry if this is the wrong place to suggest a feature (I'm new to git.)  

Movieo is the site I use the most.  I'd love for the On Plex / Download badge to appear on multiple-listing pages and not just the movie's main page.  So it would appear through the lists where it has a poster, one-line synopsis, and the RT/MetaCritic/IMDB scores, and it's ten movies per page or whatever.  

This is the page I'm thinking:  https://i.imgur.com/ytHUAzp.jpg -  I find I use that page much more frequently than drilling down into the movie's main page.  Having the button on each of those entries would be amazing.  

I'm not a developer though, this might be a situation where I don't understand, as a lay user, the technical difficulty in what I'm asking.  At any rate, keep up the great work!

**Comment by Ephellon** [comment]
Hey, this is the correct page to leave suggestions 😊 I'll look into it, thanks for the suggestion!

**Comment by matt314159** [comment]
Thanks!  It would be so convenient to just go down a list and click click click :)   Thanks for considering it!

Also - Rotten Tomatoes would be a welcome addition.

**Comment by Ephellon** [comment]
Rotten Tomatoes is already supported. Or do you mean lists on RT?

**Comment by matt314159** [comment]
Hmm, nope I don't see the badge anywhere on the movie listing page on RT.  I see it on IMDB and Movieo though.  I tried turning off adblockers too.  Weird.  I'm assuming it's the same looking button on each site.  Chrome Version 71.0.3578.98  fwiw

**Comment by Ephellon** [comment]
List on RT aren't supported yet, they don't have an ID information (your extension would ask for every single movie on the list).

**Comment by matt314159** [comment]
Oh sorry I meant the main movie page not any kind of list.  This is what I see:  https://i.imgur.com/xlCvDoO.jpg

**Comment by Ephellon** [comment]
What extension version are you using?

**Comment by matt314159** [comment]
Oh sweet!  Might be a bit redundant to Movieo but are you familiar with FlickMetrix?  https://flickmetrix.com/ that might be another cool one to add.  

Okay I'll go away now and leave you alone :)

**Comment by Ephellon** [comment]
Yes, that one was requested years ago (formerly cineshift), already working on it 🤗

**Comment by matt314159** [comment]
Oh Boy!  Thanks for all the great work.

**Comment by Ephellon** [comment]
No problem

**Comment by Ephellon** [comment]
How's this for list pages (see screenshot)?

I didn't add individual buttons to each item, instead, the extension will see what's not already on your server and provide a prompt. I wanted to keep it a Plex-like GUI, so this is what I conjured up yesterday.

![image](https://user-images.githubusercontent.com/8632548/50111297-1d85aa00-0202-11e9-825f-c9bd0302ca8e.png)

**Comment by matt314159** [comment]
Oh that's pretty sweet!  And I assume that "Grab all" type window is manually triggered by the button bottom left?  I love the direction it's going!

**Comment by Ephellon** [comment]
Yes

**Comment by Ephellon** [comment]
Just added Flickmetrix (formerly Cinesift) to v4.1

**Comment by matt314159** [comment]
I'm still away on vacation visiting my folks but had to remote in to install 4.1 and try it out and holy smokes it's amazing!!!  It's almost spooky how simple it is to add dozens of movies to Radarr at once now, wow!

Keep up the excellent work, friend!  When I get back I'll look into supporting you if I can. Send you some beer money or something.

**Comment by Ephellon** [comment]
Thanks Matt 🙂 let me know if you notice anything broken

**Comment by matt314159** [comment]
Haven't noticed anything broken, but one thing I notice if I'm doing a mass-add is that I end up with a bunch of "Movie already exists" warnings.   It would be nice if it could check Radarr for entries in addition to Plex and exclude those, too.  Not sure how complicated or difficult that would be to set up but just an observation.

**Comment by Ephellon** [comment]
I thought I'd add this already. It would get difficult with Ombi.

**Comment by knuckleheader** [comment]
Hello thanks so much for making this wonderful extension!  I find myself going to change the quality of certain movies after I start to download them.  Is there anyway to add the functionality, for those that want it, to force ask the question of quailty after clicking download.  Right now I have to go into sanzbd stop download, then go in to Radarr change quality with edit and then search again, then go back to sanzbd to delete the half downloaded file.  

Maybe I am the only one that doesn't care if I get sd quality on certain older comedies, but I want 1080p on other films.

**Comment by Ephellon** [comment]
Hi. I'm currently in training, and have about a week left before I can use my laptop, I'll start working on these when I get a chance

**Comment by Deviousretard** [comment]
Heyo, 

I have sonarr set up to download to all kinds of different folders, so it'd be great if there was an easy way to change folder on the fly. Would that be easy to implement?

**Comment by Ephellon** [comment]
Yes

**Comment by samsepiol59** [comment]
I've installed the chrome extension, and I can "only" add movies to radarr (and couchpotato) - when I click in options, I only have Plex-CouchPotato-Radarr as options. Are all the other features firefox only for the moment being?

**Comment by Ephellon** [comment]
What? Send a screenshot please

**Comment by samsepiol59** [comment]
Version 3.4 - here's a screenshot https://i.imgur.com/uq0LMX4.png!

**Comment by Ephellon** [comment]
Those features are only supported in v4.0 which is in progress right now.

You can install the most recent version via here, but it's only recommended if you know what you're doing. The major release should be coming soon otherwise.

**Comment by samsepiol59** [comment]
aaah OK, so I was missing something hehe. Thanks for the help and clarifications! Fantastic extension, can't wait for the update!

**Comment by Ephellon** [comment]
No problem. It'll be done soon

**Comment by Ephellon** [comment]
Screenshot for items marked as "done" for 06/04/2019:

![image](https://user-images.githubusercontent.com/8632548/58855274-417c6100-8665-11e9-94ff-98723609886e.png)

**Comment by Ephellon** [comment]
Stable beta version coming soon, will run through tests and push.

**Comment by Ephellon** [comment]
Stable beta version is available, see [branch:beta](https://github.com/SpaceK33z/web-to-plex/tree/beta)

**Comment by Ephellon** [comment]
Added Firefox support, update en route

**Comment by Ephellon** [comment]
Not sure if Firefox (Dev. Edition) is the problem, but installing causes fails all over the place... Postponing update for now

**Comment by Ephellon** [comment]
Got install to work properly. Continuing update as intended

**Comment by Ephellon** [comment]
Not getting any immediate problems. Will test for the rest of today and push

**Comment by Ephellon** [comment]
Added Edge (Chromium) support, update en route

**Comment by Ephellon** [comment]
Moved to [Project](https://github.com/SpaceK33z/web-to-plex/projects/4)
