### ISSUE TITLE
Mixed Content Error (HTTPS/HTTP)

### ISSUE THREAD

**Issue by naitB** [SpaceK33z/web-to-plex#64]
I downloaded and installed v4 and I got this error. 
![err](https://user-images.githubusercontent.com/20526111/50254247-5e74ee80-03bb-11e9-836c-a785764c2228.JPG)

If I choose to load unsafe script, it works fine.

**Comment by Ephellon** [comment]
Your Manager URL is HTTP not HTTPS

**Comment by Ephellon** [comment]
Radarr was loaded over HTTP, that's up to you

**Comment by Ephellon** [comment]
If you're allowed, use HTTPS, i.e. http://192.168...

**Comment by naitB** [comment]
v3.4 doesn't have this problem tho?

**Comment by Ephellon** [comment]
I'll take a look at it. Does `HTTPS` help? If not, I'll reopen this issue

**Comment by naitB** [comment]
I can't use https. I assumed v4 would work the same as v3.4.

**Comment by Ephellon** [comment]
Ok, making a fix

**Comment by naitB** [comment]
Thanks! This is such a great addon.

**Comment by Ephellon** [comment]
@naitB, please install v4.1 ([#15f50f3.zip](https://github.com/SpaceK33z/web-to-plex/files/2697038/src.zip)), and on the options page, enable the `Force Secure Connection` option (`Web to Plex | Options | Other Settings | Advance Settings | Proxy Settings | Force Secure Connection`).

**Comment by naitB** [comment]
4.1 works great, thx!

**Comment by Ephellon** [comment]
Ok, making another update to finalize

**Comment by Ephellon** [comment]
All done @naitB, please see [#83d11881.zip](https://github.com/SpaceK33z/web-to-plex/files/2697209/src.zip)
