### ISSUE TITLE
Feature: Add support for "Allocine" website

### ISSUE THREAD

**Issue by JigSawFr** [SpaceK33z/web-to-plex#66]
Hi,
A great addition will be to include allocine.fr website :)
Thank you

**Comment by Ephellon** [comment]
Has a title and year, will add later on tomorrow when I get back in town

**Comment by JigSawFr** [comment]
@Ephellon nice thank you,
On movie page, you have technical information to retrieve original title and year :)
See:
- Original Title: #synopsis-details > div.ovw-synopsis-info > div:nth-child(1) > h2
- Year: #synopsis-details > div.ovw-synopsis-info > div.more-hidden > div:nth-child(1) > span.that

With this movie page for example: http://www.allocine.fr/film/fichefilm_gen_cfilm=218476.html

**Comment by Ephellon** [comment]
Thanks @JigSawFr

**Comment by Ephellon** [comment]
Done.

![image](https://user-images.githubusercontent.com/8632548/59294389-0078e380-8c47-11e9-81b8-678933e80495.png)
