### ISSUE TITLE
Feature: Add support for MovieMeter and/or Pass the Popcorn

### ISSUE THREAD

**Issue by keinflausaus** [SpaceK33z/web-to-plex#68]
I just found this extension! Awesome work :) it fits my needs greatly - since I use both Plex and Radarr extensively. I also frequently use the Dutch movie website Moviemeter.nl and get torrents and movie suggestions from Passthepopcorn.com, and I thought that it would add extra functionality if these websites could be supported!

**Comment by Ephellon** [comment]
passthepopcorn is invite only, but there was an old branch that supported it. I'll look into it; also, if you're good at programming in JS, see my branch and look at the "plugins."

**Comment by Ephellon** [comment]
Added MovieMeter. As Pass the Popcorn is still invite only, I have no way of adding it correctly.

**Comment by Ephellon** [comment]
![image](https://user-images.githubusercontent.com/8632548/59295070-6dd94400-8c48-11e9-88c9-e45ec6f22fca.png)

**Comment by Ephellon** [comment]
Looking to add passthepopcorn: looking for BETA testers

**Comment by Ephellon** [comment]
No way of testing PtP, closing issue for now
