### ISSUE TITLE
Issue: Using websites that are not IMDB

### ISSUE THREAD

**Issue by darkness7268** [SpaceK33z/web-to-plex#69]
Hello, I am running version 3.4 installed from the chrome web store. Using Version 71.0.3578.98 (Official Build) (64-bit) on Windows 10. This extension works amazingly with IMDB with my plex and couchpotato linked and working. I, however, cannot get the plugin to load on other websites like netflix, hulu, and myanime list (These are the three I have tested). The extension is greyed out as if t is not loaded. I open IMDB and it works instantly. I have tried allowing on click, all sites, and manually added the mentioned sites. I do not know if I simply and missing where the 'on plex' or 'download' buttons are supposed to be or if it is not loading like I think.

Note: I do have other extensions installed. Although I have disabled all but web to plex to test with no success
<img width="24" alt="capture" src="https://user-images.githubusercontent.com/5225579/51431195-63a3a400-1bda-11e9-8bf3-443d91fecbf6.PNG"> Here is the plugin when on hulu and such.

I am new to couch potato but I have it setup and working. Thanks for any help and for working on the awesome extension!

**Comment by Ephellon** [comment]
Upgrade to v4

**Comment by Ephellon** [comment]
If v4 isn't on the main branch, see my fork and install from there
