### ISSUE TITLE
Feature/Wishlist:  Import an actual (CSV) list.  

### ISSUE THREAD

**Issue by matt314159** [SpaceK33z/web-to-plex#70]
Hey! Still loving the Web to Plex plugin.  I'm in an interesting situation and as a last-ditch effort thought I'd see if it's something that could be easily added in to this extension.  I'm slowly ramping down my personally-hosted plex server in favor of a cloud instance on bytesized hosting and putting my data in an unlimited google drive with rclone.  I guess that part's irrelevant.  Anyway I want to import my current movie list into the new Radarr instance and have it re-download everything.  I got into the nzbdrone.db database and exported a table that has the IMDB ID # & Movie Title of all my titles, nice and clean.  

Would it be trivial to add a back-door to this app where you could feed it a specific CSV and import them to Radarr?  

All of the existing functionality I have tried hits road-blocks.  For instance, TMDB lets you import a CSV list but only to your personal watch list and not a list you can share publicly to let Radarr attach and sync it.  IMDB and Trakt don't seem to have import functions.  

But I'm wondering if, since you've already written a framework for adding stuff into Plex would a manual data source be an option?  

Or do you have any alternative methods or suggestions?  I'd actually like to add them into Radarr unmonitored and then do like a page at a time manually sending them to my download client over the course of several weeks.  

Thoughts? 

EDIT - I just realized that Movieo does allow list imports. I can make a list on that and then add them page-by-page via the web to plex extension!  I didn't see a delete button but thought I'd let you know I figured it out!

**Comment by Ephellon** [comment]
Great, thanks matt-π 👀
