### ISSUE TITLE
Feature/Wishlist: Provide simultaneous login to radarr AND sonarr

### ISSUE THREAD

**Issue by bn3d** [SpaceK33z/web-to-plex#71]
I really love the extension, but what bugs me is that I have to choose if it works only for movies or only for TV series with the current settings provided, but the websites that are supported are a mix of both. It would be great to have an option to login in radarr and sonarr simultaneously so it wouldn't matter what kind of content we are watching on the supported websites. 

Thank you for the amazing work you already did and I hope you keep making the extension better, it already is the best of it's kind.

**Comment by Ephellon** [comment]
That's already a feature... What version are you using?

You should be able to login to each supported service altogether

**Comment by Ephellon** [comment]
If you open a new tab, the extension forces resources to the new tab (if it's a supported site). I've already started working on a "threading" feature

**Comment by bn3d** [comment]
I am using the Firefox extension version 3.4 and in it's preferences I have Plex settings, Couch potato settings and Radarr settings drop-downs(no Sonarr option). I have put in the necessary information for my Plex and Radarr installations and they work fine, but for example if I go to IMDB on a page of a TV show I only get the info if the show is available on the Plex server and I cannot click the button to send it to Sonarr to be monitored, like it is doing with movies and Radarr. I tried to copy the Sonarr IP and authentication key to the Couch Potato section, but it does not seem to work. Am I doing something wrong?

**Comment by Ephellon** [comment]
If possible, use chrome and install v4

**Comment by Ephellon** [comment]
https://github.com/Ephellon/web-to-plex

**Comment by bn3d** [comment]
I would like to stay with Firefox. So it is not currently possible to install v4 on Firefox? If so is there a way to install it manually on Firefox?

**Comment by Ephellon** [comment]
Not yet, it'll have to be ported to the current version, see the "Firefox Support" issue

**Comment by bn3d** [comment]
Thank you for the information. I would continue to use the extension as is and I hope to be able to use its full potential with Firefox in the future. Thanks again
