### ISSUE TITLE
Where can I get the latest version (with Sonarr support)

### ISSUE THREAD

**Issue by Clownfused** [SpaceK33z/web-to-plex#72]
I can't seem to find the version of this Chrome extension that has Sonarr support... using this link https://chrome.google.com/webstore/detail/web-to-plex/kmcinnefmnkfnmnmijfmbiaflncfifcn?hl=en takes me to what I think is an old version (3.4 Updated May 19, 2018) that only seems to have Radarr support.

Can someone tell me where I can get the latest version of this?

Thanks!

**Comment by Ephellon** [comment]
The link to this, except, replace "spacek33z" with "ephellon"

**Comment by Ephellon** [comment]
https://github.com/ephellon/web-to-plex

**Comment by Clownfused** [comment]
Thank you

**Comment by lostandlost** [comment]
Is there an updated version for firefox?

**Comment by Ephellon** [comment]
No, not yet

**Comment by Ephellon** [comment]
Lol. Yes. See the beta-branch
