### ISSUE TITLE
Select a server first! or Can't save.

### ISSUE THREAD

**Issue by alonewestand** [SpaceK33z/web-to-plex#73]
Clicking login after entering plex info grays out the "save" option. Entering Radarr info first and then entering plex info and hitting "save" makes it say "select a server first!" 

So I can't select the server without not being able to save, and I can't save without selecting the server.

![2019-05-04 08_14_22-Extensions](https://user-images.githubusercontent.com/39413174/57178842-bb41e480-6e44-11e9-9ec3-2b9e61baebd8.png)

**Comment by Ephellon** [comment]
What version are you using?
