### ISSUE TITLE
Multiple Movies In Plex Showing Not in Plex

### ISSUE THREAD

**Issue by Simpuhl** [SpaceK33z/web-to-plex#84]
For example 

https://www.imdb.com/title/tt0093177/
https://i.imgur.com/uTG0W9P.png 

Its in my plex though...

https://i.imgur.com/vhVmHwA.jpg

I can get you a lot more examples if you want. Id say its 1 ever 20 or so,.

**Comment by Ephellon** [comment]
Please update to v4 when available

**Comment by Simpuhl** [comment]
Thanks so much for the quick response. Its not in the Chrome Store yet so Ill wait :)
