### ISSUE TITLE
Feature: Add "Plex Web Player" as a supported site

### ISSUE THREAD

**Issue by mattssn11** [SpaceK33z/web-to-plex#98]
I was wondering if you could make this so that you are able to do the same thing from a Plex Library, like another user shared library.

**Comment by Ephellon** [comment]
@mattssn11 I'm sorry, I'm not sure what you mean. Do you mean choose someone else's library to check media from?

**Comment by Ephellon** [comment]
If so, you can select the server you want to check, from the drop down menu (all versions)

**Comment by Ephellon** [comment]
I'm currently in class, but I'll try responding during my breaks

**Comment by mattssn11** [comment]
Sorry should have been more specific, but say I have a friend that shares
his Plex library with me, I thought it would be cool to have the same
options on like the Plex webplayer, that you have on all the other
supported sites, so it will take the movie page you are on and check your
specific library to see if you have it, and if not then send it to your
Radarr etc.

**Comment by Ephellon** [comment]
Oh. Understood, that's a great idea, no problem

**Comment by Ephellon** [comment]
I'll start working on it in an hour or so, gotta eat first

**Comment by mattssn11** [comment]
Awesome! thanks a ton!

**Comment by Ephellon** [comment]
All done... had to change some extra code...

**Comment by Ephellon** [comment]
Pushing update commit in 10 minutes

**Comment by Ephellon** [comment]
Also going to add the "download file" feature: `*.plex.direct:port/*/file.mp4?*`

**Comment by Ephellon** [comment]
Not able to complete this at the moment, will need more API information
